name = "izi-house-web"
main = ".next/standalone/server.js"
pages_build_output_dir = ".next/static"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"
